### ISSUE TITLE
There is no data/OpticalFlow.cpp file in this repository

### ISSUE THREAD

**Issue by li-ren** [AlexanderParkin/CASIA-SURF_CeFA#3]
As the title, the file didn't be put on the repository.
I saw the comment on README.md. The modification of the file is about removing logs spamming to console.
I try to remove them by myself. However, I found there are some error logs during training phase.

"All the pixels are invalid in estimation Laplacian noise!!!
Something severely wrong happened!!!"

Are these error logs OK for this project?

Thank you for taking the time to read this issue.

**Comment by oleggrinch** [comment]
Hello, thanks for the notice, we added .cpp file and updated README.
This error is OK, it occurs when some data regions are filled with black pixels
